name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Frontend lint and typecheck
  frontend-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Intentionally wrong version (should be 20+)
        cache: 'npm'
        cache-dependency-path: web/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run lint
      run: npm run lint
    
    - name: Run typecheck
      run: npm run typecheck  # Wrong script name (should be type-check)

  # Backend lint, typecheck, and tests
  backend-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Intentionally wrong version
        cache: 'npm'
        cache-dependency-path: api/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run lint
      run: npm run lint
    
    - name: Run typecheck
      run: npm run typecheck
    
    - name: Run unit tests
      run: npm run test:unit
      env:
        DATABASE_URL: "postgresql://test:test@localhost:5432/test"
    
    - name: Run integration tests
      run: npm run test:integration
      env:
        DATABASE_URL: "postgresql://test:test@localhost:5432/test"

  # Docker build test (intentionally missing setup)
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build API Docker image
      run: docker build -t skillgaug-api ./api
    
    - name: Build Web Docker image
      run: docker build -t skillgaug-web ./web
    
    # Missing: Docker daemon setup, registry login, etc.
    - name: Test Docker Compose
      run: docker-compose up --build -d  # Wrong command (should be docker compose)