name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # Security and dependency checks
  security-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm ci
    
    - name: Audit dependencies (API)
      run: npm audit --audit-level moderate
      working-directory: ./api
    
    - name: Audit dependencies (Web)
      run: npm audit --audit-level moderate
      working-directory: ./web
  
  # Code quality checks
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm ci
    
    - name: Install API dependencies
      run: npm ci
      working-directory: ./api
    
    - name: Install Web dependencies
      run: npm ci
      working-directory: ./web
    
    - name: Check formatting (API)
      run: npm run format:check
      working-directory: ./api
    
    # Note: Web project doesn't have format:check script yet
    # - name: Check formatting (Web)
    #   run: npm run format:check
    #   working-directory: ./web